name: Terraform Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5  # Use the desired Terraform version

      - name: Initialize Terraform
        run: terraform init
        #working-directory: ./path-to-your-terraform-config

      - name: Plan Terraform Changes
        run: terraform plan
        #working-directory: ./path-to-your-terraform-config

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        #working-directory: ./path-to-your-terraform-config
        env:
          TF_CLI_ARGS: "-input=false"  # Automatically approve changes without asking for confirmation

      - name: Deploy Complete
        run: |
          echo "Terraform deployment complete."
