name: Terraform Apply

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5  # Adjust the Terraform version

      - name: Configure AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Initialize and Apply Terraform
        run: |
          ls
          terraform init
          terraform destroy -auto-approve
        env:
          TF_CLI_ARGS: "-input=false"  # Automatically approve changes without asking for confirmation

